
meat:
  - курица
  - бык
  - Свиная 
  - вырезка
  - грудинка
  - Оленина
  - Баранина
  - Конина
  - Цыпленок
  - Свинина
  - Говядина
  - гуся
  - кролика
  - Куриная 
  - грудка
  - Сосиски 
  - свиные
  - Мясо 
  - индейки
  - Фарш 
  - Бекон
  - Ветчина
  - Колбаса 
  - салями
  - Говяжья 
  - колбаса
  - Гусиная 
  - Курица
  - Мясо
  - Сосиски 
  - Окорочка
  - сердечки
  - утки
  - желудочки
  - Буженина
  - ножки
  - крылышки
  - язык
  - Сардельки 
  - корейка
  - Сало
  - колбаски
  - ребрышки
  - перепела
  - окорок
  - курица
  - Сальтисон
  - Балык 
  - Телятина
  - Кровяная 
  - Лягушачьи
  - лапки
  - Ноги 
  - Ливерная 
  - Тушенка 
  - Бастурма
  - поросенок
  - Дичь
  - Колбаса 
  - Шпикачки
  - крокодила
  - страуса
  - змеи
  - Окорок 
  - утка
  - птицы
  - сало
  - бедра
  - Шея 
  - Бычьи
  - шейки
  - Спинки 
  - хвосты
  - Вымя 
  - Крыло
  - Баранья 
  - потроха
  - стейк
  - Грудка 
  - уши
  - гузка
  - сердце
  - Ребра 
  - легкое
  - желудок
  - огузок
  - сердце
  - мозги
  - колбаса
  - Языковая 
  - Конская 
  - Панчетта
  - Котлетный
  - Ростбиф
  - медведя
  - кабана
  - Козлятина

seafood:
  - Анчоусы
  - Белуга
  - Водоросли
  - Вобла
  - Горбуша
  - Ёрш
  - Жерех
  - Зубатка
  - камбала
  - Карась
  - Карп
  - Кета
  - Кефаль
  - Кижуч
  - спирулина
  - Ламинария
  - Морская капуста
  - нори
  - порфира
  - комбу
  - далс
  - уми будо
  - лиму
  - ульва
  - вакаме
  - кантен
  - Кальмар
  - Осьминог
  - Крабовые
  - Креветки
  - Лангуст
  - Лобстер
  - Мидии
  - Трепанг
  - Устрица
  - Раки
  - Морской гребешок
  - рапаны
  - амур
  - бельдюга
  - камбала
  - ерш
  - килька
  - клыкач
  - корюшка
  - красноглазка
  - красноперка
  - лемонема
  - лещ
  - луфарь
  - лосось 
  - летрин
  - макрель
  - макрурус 
  - хоки
  - мерланг
  - Сельдь
  - Тунец
  - треска
  - форель
  - осетр
  - горбуша
  - судак
  - сардины
  - Сайра
  - шпроты
  - хек
  - семга
  - тунец
  - сом
  - стерлядь
  - угорь
  - щука
  - Килька
  - Кальмары
  - скумбрия
  - пеленгас
  - скумбрия
  - толстолобик
  - Каракатица
  - Тунец
  - Хоккигай 
  - моллюск
  - Икра масаго
  - Рыба пангасиус
  - Икра мойвы
  - Рыба пеламида
  - Сушеные кальмары
  - Икра горбуши
  - Красная икра
  - Черная икра
  - налим
  - анчоусы
  - скумбрия
  - сельдь
  - Сардины
  - треска
  - кальмара
  - мидии
  - морская капуста
  - кальмаров
  - Бычки
  - килька
  - Икра минтая
  - Икра
  - лосось
  - крабы
  - осьминоги
  - леща
  - навага
  - семги
  - карп
  - осьминог
  - скумбрия
  - щуки
  - кальмары
  - форель
  - толстолобик
  - креветки
  - щука
  - мойва
  - сом
  - карп
  - горбуша
  - Ястычная икра
  - палтус
  - Рыба ставрида
  - Морская капуста
  - Мясо трубача
  - Икра палтуса
  - барабулька 
  - султанка
  - Икра улиток
  - Морепродукты
  - Кукумария
  - Рыба фугу
  - Морские ежи
  - Икра морских
  - Акула
  - кит
  - креветки
  - черепаха
  - Сельдь
  - Килька
  - скумбрия
  - Форель
  - Мидии
  - мойва
  - форель
  - скат
  - хамса
  - тюлька
  - Мойва
  - окунь
  - салака
  - чавыча
  - хариус
  - рыбец

spicy:
  - острый

